{
 "title": "Ataka",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Flags per minute per exploit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT concat(exploit_histories.service, ' (',left(exploits.docker_name, -17), ')'), COALESCE(COUNT(flags.id), 0) as \" \" , date_trunc('minute',executions.timestamp) \nFROM executions\nleft join flags on flags.execution_id = executions.id \ninner join jobs on jobs.id = executions.job_id\ninner join exploits on jobs.exploit_id = exploits.id\ninner join exploit_histories on exploit_histories.id = exploits.exploit_history_id\nGROUP BY concat(exploit_histories.service, ' (',left(exploits.docker_name, -17), ')'), date_trunc('minute',executions.timestamp) \nORDER BY date_trunc('minute',executions.timestamp)\n"
    }
   ]
  },
  {
   "title": "Flags overall",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(flags.id) from flags where flags.status = 'OK'"
    }
   ]
  },
  {
   "title": "Flags per Minute",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(COUNT(flags.id), 0) as \" \" , date_trunc('minute',executions.timestamp) \nFROM executions\nleft join flags on flags.execution_id = executions.id \ninner join jobs on jobs.id = executions.job_id\ninner join exploits on jobs.exploit_id = exploits.id\nWHERE date_trunc('minute',executions.timestamp) < date_trunc('minute',now())\nGROUP BY date_trunc('minute',executions.timestamp) \nORDER BY date_trunc('minute',executions.timestamp)"
    }
   ]
  },
  {
   "title": "lol",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select flags.status, count(flags.status) from flags group by flags.status"
    }
   ]
  },
  {
   "title": "Flags overall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(COUNT(flags.id), 0) as \" \" , date_trunc('minute',executions.timestamp) \nFROM executions\nleft join flags on flags.execution_id = executions.id \ninner join jobs on jobs.id = executions.job_id\ninner join exploits on jobs.exploit_id = exploits.id\nGROUP BY date_trunc('minute',executions.timestamp) \nORDER BY date_trunc('minute',executions.timestamp)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 14 },
   "options": {
    "content": "<img src=\"https://c.tenor.com/CgGUXc-LDc4AAAAC/tenor.gif\" /> "
   }
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT exploit_histories.service as challenge, executions.timestamp, exploits.docker_name, exploits.author, targets.ip, jobs.status, flags.status as flagstatus\nfrom exploits\ninner join jobs on jobs.exploit_id = exploits.id\ninner join executions on jobs.id = executions.job_id\ninner join targets on executions.target_id = targets.id\ninner join flags on flags.execution_id = executions.id\ninner join exploit_histories on exploit_histories.id = exploits.exploit_history_id"
    }
   ]
  }
 ]
}